### ISSUE TITLE
Good use case and settings

### ISSUE THREAD

**Issue by PierreMarieRiviere** [esimov/forensic#1]
First, say nice work. 

Is this a good app to use on document forging check? (id cards etc)

If so what would be the optimal settings for this use case?

**Comment by esimov** [comment]
This app is capable of recognizing identical image parts, which does not means that is capable recognizing any kind of forged images. So it depends of the use case you wish to use. Also as it is mentioned in the documentation does not guarantee 100% accuracy.

**Comment by PierreMarieRiviere** [comment]
This is an id card i've forged by copy-moving parts.

[https://ibb.co/3RsNcKY](url)

 i've tried the app with several such images with little results (many false positives, results seem pretty random). Wondering if the app is just not accurate with documents or if I could improve the results with proper settings.

**Comment by esimov** [comment]
Sorry but the provided link is broken. You have to play with the settings to get a better accuracy. The accuracy depends on the image composition, the forged region size etc.

**Comment by PierreMarieRiviere** [comment]
ok thanks

**Comment by esimov** [comment]
Please send me the image and i will look into it.

**Comment by PierreMarieRiviere** [comment]
the link does work on my end when copy pasted in the url bar

**Comment by esimov** [comment]
Running the library over this image with the following settings is showing that is forged.
```bash
$ forensic -in ~/Desktop/sample-id-card.jpg -out ~/Desktop/out.png -bs=6`.

Number of forged blocks detected:  34
100% the image is forged!

```
The more condensed/intense (read as red) a detected forged region is, the bigger is the probability the image is forged, but this image in particular is not really suitable for forge detection.

**Comment by PierreMarieRiviere** [comment]
Yes the app recognizes the image is forged, but this same goes for non-forged similar documents ```100% the image is forged!``` and the number / ratio of blocks detected as forged does not differ by much.

**Comment by PierreMarieRiviere** [comment]
This is a similar document (not forged) and the corresponding heat map. 
https://ibb.co/ZVSy9vd
https://ibb.co/LYX1Ymf
```
Number of forged blocks detected:  1514
87% the image is forged!
```
I took the pic myself the image is genuine.

**Comment by esimov** [comment]
I have tried with the forgery threshold (`-ft`) set to 430 and it's not showing as forged. This flag is used to set a forgery threshold above an image is considered forged if forged blocks are detected. On images with very identical parts it's better to increase this value to reduce the false positive detection rates.

```
Generate:  135894 / 135894 [=====================================================================================================================================================================] 100.00% 0s
Analyze:  1223045 / 1223045 [====================================================================================================================================================================] 100.00% 0s
Detect:  16765 / 16765 [=========================================================================================================================================================================] 100.00% 0s
Filter:  16692 / 16693 [=========================================================================================================================================================================]  99.99% 0s

Number of forged blocks detected:  0
100% the image is NOT forged!

Done in: 1.90s

```

**Comment by PierreMarieRiviere** [comment]
Nice! I'll take this direction, make a few test with different images and revert to you here with the results!
Thanks for the guidance

**Comment by olekukonko** [comment]
@TheDApact any update on your test?

**Comment by jtlz2** [comment]
@PierreMarieRiviere What happened with the above?
